# Generated by Django 5.2.3 on 2025-06-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('describe', models.TextField(blank=True, max_length=1000, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
    ]
