# Generated by Django 5.2.3 on 2025-06-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
